---
dependencies:
- name: "activiti-cloud-identity"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "0.0.21"
- name: "activiti-cloud-query"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.914"
  condition: "application.activiti-cloud-query.enabled,activiti-cloud-query.enabled"
- name: "rabbitmq-ha"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "1.38.1"
  condition: "application.rabbitmq.enabled,rabbitmq.enabled"
  alias: "rabbitmq"
- name: "postgresql"
  repository: "https://kubernetes-charts.storage.googleapis.com"
  version: "6.3.9"
  condition: "application.postgres.enabled,postgres.enabled"
  alias: "postgres"
- name: "runtime-bundle"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.914"
  condition: "application.runtime-bundle.enabled,runtime-bundle.enabled"
- name: "activiti-cloud-connector"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.914"
  condition: "application.activiti-cloud-connector.enabled,activiti-cloud-connector.enabled"
- name: "activiti-cloud-modeling"
  repository: "https://activiti.github.io/activiti-cloud-helm-charts/"
  version: "7.1.914"
  condition: "activiti-cloud-modeling.enabled,modeling.enabled"
